name: cumulocity-devicemanagement-agent
version: '1'
summary: Cumulocity Cloud Connector
description: |
  Cumulocity Cloud Connector
base: core20
confinement: devmode
architectures:
  - build-on: [arm64, armhf, amd64]


parts:
  c8ydm:
    plugin: python
    python-version: python3
    source: .
    requirements:
      - requirements.txt
apps:
  c8ydm-start:
    command: bin/c8ydm
  c8ydm-stop:
    command: bin/c8ydm.stop
  c8ydm:
    command: bin/c8ydm
    daemon: simple
    restart-condition: always
    stop-command: bin/c8ydm.stop