name: cumulocity-devicemanagement-agent
version: '1'
summary: Cumulocity Cloud Connector
description: |
  Cumulocity Cloud Connector
base: core20
confinement: strict


parts:
  c8ydm:
    plugin: python
    source: .
    requirements:
      - requirements.txt
apps:
  c8ydm-start:
    command: bin/c8ydm.start
  c8ydm-stop:
    command: bin/c8ydm.stop
  c8ydm:
    command: bin/c8ydm
    daemon: simple
    restart-condition: always
    stop-command: bin/c8ydm.stop