name: cumulocity-devicemanagement-agent
version: '1'
summary: Cumulocity Cloud Connector
description: |
  Cumulocity Cloud Connector
base: core22
confinement: devmode


parts:
  c8ydm:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
apps:
  c8ydm-start:
    command: c8ydm
  c8ydm-stop:
    command: c8ydm.stop
  c8ydm:
    command: c8ydm
    daemon: simple
    restart-condition: always
    stop-command: c8ydm.stop